"""initial schema"""

import sqlalchemy as sa

from alembic import op

revision = "28bd115d59a7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "listings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("import_scope", sa.String(length=64), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("brand", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("generation", sa.String(length=100), nullable=True),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("price_usd", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("mileage_km", sa.Integer(), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("region", sa.String(length=100), nullable=True),
        sa.Column("fuel_type", sa.String(length=100), nullable=True),
        sa.Column("engine_volume", sa.Float(), nullable=True),
        sa.Column("transmission", sa.String(length=100), nullable=True),
        sa.Column("drive_type", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("seller_type", sa.String(length=100), nullable=True),
        sa.Column("vin", sa.String(length=30), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "external_id", name="uq_listing_source_external"),
    )
    op.create_index(
        "ix_listing_comparables",
        "listings",
        ["source", "is_active", "brand", "model", "year"],
        unique=False,
    )
    op.create_table(
        "deal_scores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("estimated_market_price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("discount_percent", sa.Float(), nullable=True),
        sa.Column("estimated_repair_cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("estimated_expenses", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("potential_profit", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("liquidity_score", sa.Float(), nullable=False),
        sa.Column("risk_score", sa.Float(), nullable=False),
        sa.Column("total_score", sa.Float(), nullable=True),
        sa.Column("explanation", sa.JSON(), nullable=False),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["listing_id"], ["listings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("listing_id"),
    )
    op.create_table(
        "listing_photos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("photo_url", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["listing_id"], ["listings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_listing_photos_listing_id"), "listing_photos", ["listing_id"], unique=False
    )
    op.create_table(
        "price_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("price_usd", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["listing_id"], ["listings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_price_history_listing_id"), "price_history", ["listing_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_price_history_listing_id"), table_name="price_history")
    op.drop_table("price_history")
    op.drop_index(op.f("ix_listing_photos_listing_id"), table_name="listing_photos")
    op.drop_table("listing_photos")
    op.drop_table("deal_scores")
    op.drop_index("ix_listing_comparables", table_name="listings")
    op.drop_table("listings")
    op.drop_table("import_runs")
    # ### end Alembic commands ###
